"""Uebersetzungskatalog fuer manual.py."""

STRINGS = {
    "manual.category_navigation": {"de": "Navigation", "en": "Navigation"},
    "manual.category_content": {"de": "Seite & Inhalt", "en": "Page & Content"},
    "manual.category_storage": {"de": "Ablage & Verlauf", "en": "Storage & History"},
    "manual.category_ai": {"de": "KI-SysOp", "en": "AI SysOp"},
    "manual.category_system": {"de": "System & Konfiguration", "en": "System & Configuration"},
    "manual.category_games": {"de": "Spielhalle", "en": "Arcade"},

    "manual.nr_short": {"de": "Link Nr. anwaehlen", "en": "Select link by number"},
    "manual.nr_long": {"de": "Jeder Link im Text traegt eine Nummer in eckigen Klammern, z.B. 'Mehr lesen[12]'. Tippe die Nummer und Enter, um dorthin zu wechseln. Das geht auch direkt am -- MORE -- Prompt, ohne die Seite zu Ende zu blaettern.", "en": "Every link in text carries a number in square brackets, e.g. 'Read more[12]'. Type the number and Enter to jump there. Works directly at the -- MORE -- prompt too, without scrolling to the end."},

    "manual.d_short": {"de": "Seite anwaehlen (dial) oder Favoriten-Kurzwahl", "en": "Select page (dial) or bookmark shortcut"},
    "manual.d_long": {"de": "'d heise.de' waehlt eine Seite an; das Schema https:// wird ergaenzt. Neben http/https verstehen wir die Retro-Netze gopher:// und gemini://. Mit einer Zahl statt einer URL ('d 3') waehlst du Favorit Nr. 3 aus dem Bookmark-Register — die Kurzwahl.", "en": "'d heise.de' selects a page; https:// is added automatically. Besides http/https, we support retro nets gopher:// and gemini://. With a number instead of URL ('d 3') you select bookmark no. 3 from the register — the quick dial."},

    "manual.s_short": {"de": "Im Netz suchen", "en": "Search the net"},
    "manual.s_long": {"de": "Sucht den Begriff im Netz und laedt die Trefferliste als BBS-Seite mit nummerierten Links. Ist Firecrawl konfiguriert (Menue 'c'), laeuft die Suche ueber dessen Such-API; sonst ueber DuckDuckGo, dessen HTML-Seite automatisierte Abrufe allerdings oft blockt. Weiterleitungs-Links werden automatisch auf das echte Ziel aufgeloest.", "en": "Searches the term on the net and loads the results as a BBS page with numbered links. If Firecrawl is configured (menu 'c'), the search uses its search API; otherwise DuckDuckGo, whose HTML page often blocks automated requests though. Redirect links are automatically resolved to their actual target."},

    "manual.b_short": {"de": "Zurueck", "en": "Back"},
    "manual.b_long": {"de": "Geht eine Seite im Verlauf zurueck. Jede Node hat ihren eigenen Zurueck-Stapel.", "en": "Go back one page in history. Each node has its own back stack."},

    "manual.f_short": {"de": "Vorwaerts", "en": "Forward"},
    "manual.f_long": {"de": "Geht wieder vorwaerts, nachdem du mit 'b' zurueckgegangen bist.", "en": "Go forward again after going back with 'b'."},

    "manual.r_short": {"de": "Seite neu laden", "en": "Reload page"},
    "manual.r_long": {"de": "Laedt die aktuelle Seite erneut, ohne einen neuen Verlaufseintrag anzulegen.", "en": "Reloads the current page without creating a new history entry."},

    "manual.l_short": {"de": "Link-Tafel, optional gefiltert", "en": "Link board, optionally filtered"},
    "manual.l_long": {"de": "Zeigt alle Links der Seite als eigene Tafel mit Nummer, Beschriftung und Ziel-URL. Mit einem Wort dahinter ('l ki') werden nur Links gezeigt, deren Text oder URL das Wort enthaelt; die Original-Nummern bleiben erhalten. Am Ende der Tafel kannst du direkt eine Nummer anwaehlen.", "en": "Shows all page links as a board with number, label, and target URL. With a word after it ('l ai') only links whose text or URL contain the word are shown; original numbers are preserved. At the end of the board you can select a number directly."},

    "manual.slash_short": {"de": "In der Seite suchen", "en": "Search in page"},
    "manual.slash_long": {"de": "Springt zur naechsten Fundstelle in der aktuellen Seite und zeigt ab dort an. '/' allein sucht mit demselben Wort weiter. Bei einer neuen Seite beginnt die Suche von vorn.", "en": "Jumps to the next match in the current page and displays from there. '/' alone searches with the same word again. On a new page, search starts from the beginning."},

    "manual.n_short": {"de": "Nodes (Tabs) auflisten oder wechseln", "en": "List or switch nodes (tabs)"},
    "manual.n_long": {"de": "Die BBS hat vier Leitungen (Nodes). 'n' listet sie mit ihrer aktuellen Seite auf, 'n2' wechselt auf Node 2. Jede Node haelt ihre eigene Seite und ihren eigenen Zurueck-/Vorwaerts-Verlauf — wie Tabs, nur nostalgischer.", "en": "The BBS has four lines (nodes). 'n' lists them with their current page, 'n2' switches to node 2. Each node holds its own page and its own back/forward history — like tabs, only more nostalgic."},

    "manual.fm_short": {"de": "Eingabemaske: Suchfelder der Seite ausfuellen", "en": "Input form: fill in the page's search fields"},
    "manual.fm_long": {"de": "Zeigt die Formulare der Seite als BBS-Eingabemaske. 'fm' oeffnet die einzige Maske direkt oder laesst waehlen, 'fm 2' nimmt die zweite. Danach wird Feld fuer Feld gefragt; leere Eingabe uebernimmt die Vorbelegung, bei Auswahllisten waehlt eine Nummer. Abgeschickt wird durch Waehlen der zusammengebauten Adresse. Es gehen nur GET-Formulare — also Suchfelder und Filter. Logins und POST-Formulare brauchen eine Sitzung und bleiben aussen vor.", "en": "Shows the page's forms as a BBS input mask. 'fm' opens the only form directly or lets you choose; 'fm 2' takes the second one. Then each field is asked for; an empty entry keeps the default, and for drop-down lists a number selects. Submitting simply dials the assembled address. Only GET forms work — search fields and filters. Logins and POST forms need a session and are left out."},

    "manual.we_short": {"de": "Wetterstation und Weltzeit", "en": "Weather station and world clocks"},
    "manual.we_long": {"de": "Zeigt das Wetter deines Ortes als ASCII-Himmel: aktuelle Werte, Sonnenauf- und -untergang, drei Tage Vorschau und darunter die Weltzeituhren des SysOp. Die Daten kommen von Open-Meteo, ohne Schluessel und ohne Konto, und werden 30 Minuten lang wiederverwendet; 'we r' frischt sofort auf. Ort, Einheiten und Uhren stellst du unter 'c' > Wetter & Uhr ein. Ohne Ort bleiben nur die Uhren.", "en": "Shows your location's weather as an ASCII sky: current readings, sunrise and sunset, a three-day forecast and below it the SysOp's world clocks. The data comes from Open-Meteo, no key and no account, and is reused for 30 minutes; 'we r' refreshes immediately. Location, units and clocks live under 'c' > Weather & clock. Without a location only the clocks remain."},
    "manual.bu_short": {"de": "Bulletin-Board des SysOp", "en": "The SysOp's bulletin board"},
    "manual.bu_long": {"de": "Zeigt die Meldungen, die der SysOp aus deinen News-Quellen geschrieben hat — als Liste mit Cursor: ↑↓ waehlt eine Meldung, ENTER waehlt den Artikel an, ESC geht zurueck. Ohne steuerbares Terminal bleibt die Seite mit [n]-Links. Ist die Quelle ein RSS- oder Atom-Feed, braucht es dafuer KEINE KI: eine Feed-Meldung ist bereits eine fertige Schlagzeile und wird unveraendert uebernommen. Nur eine normale Nachrichtenseite muss der SysOp lesen — dafuer braucht es einen Schluessel. Du kannst beliebig viele Quellen eintragen (bis 8) und Feeds und Seiten frei mischen: Alle Quellen werden auf dieselbe Form gebracht und zu EINER Liste gemischt, neuste zuerst, Doppelte fliegen raus. Jede Zeile zeigt Herkunft und Alter ('heise.de · vor 10 min'). Schlagzeilen von einer normalen Seite haben gar kein Datum und stehen deshalb hinter den datierten — ein erfundenes Datum wuerde echte verdraengen. Die Meldungen entstehen beim Einwaehlen im Hintergrund und werden standardmaessig 6 Stunden lang wiederverwendet (Kadenz 0 = bei jeder Anwahl); 'bu r' erzwingt eine sofortige Auffrischung. Quellen, Kadenz und Anzahl stellst du unter 'c' > Bulletins ein; in der Quellenliste schaltet ENTER eine Quelle stumm, 'a' nimmt eine neue auf, 'x' wirft sie raus.", "en": "Shows the bulletins the SysOp wrote from your news sources — as a list with a cursor: ↑↓ picks a bulletin, ENTER dials the article, ESC goes back. Without a controllable terminal you get the page with [n] links instead. If the source is an RSS or Atom feed, NO AI is involved: a feed entry already is a finished headline and is taken as it stands. Only a plain news page has to be read by the SysOp, and that needs a key. You may add as many sources as you like (up to 8) and mix feeds and pages freely: every source is normalised to the same shape and merged into ONE list, newest first, with duplicates dropped. Each line shows where it came from and how old it is ('heise.de · 10 min ago'). Headlines from a plain page carry no date at all and therefore follow the dated ones — a made-up date would push real ones aside. The bulletins are written in the background during dial-in and reused for 6 hours by default (cadence 0 = every dial-up); 'bu r' forces an immediate refresh. Sources, cadence and count live under 'c' > Bulletins; in the sources list ENTER mutes a source, 'a' adds one, 'x' throws it out."},
    "manual.rss_short": {"de": "Message Base: Feed als BBS-Menue", "en": "Message base: Feed as BBS menu"},
    "manual.rss_long": {"de": "Oeffnet den RSS- oder Atom-Feed der aktuellen Seite als klassische Message Base: Schlagzeilen als nummerierte Liste mit kurzem Anriss. Ohne Argument wird der im HTML angegebene Feed genommen, sonst werden uebliche Pfade wie /feed oder /rss.xml probiert. Mit 'rss <url>' oeffnest du jeden beliebigen Feed direkt.", "en": "Opens the RSS or Atom feed of the current page as a classic message base: headlines as a numbered list with brief excerpt. Without argument, uses the feed specified in HTML; otherwise tries common paths like /feed or /rss.xml. With 'rss <url>' you open any feed directly."},

    "manual.o_short": {"de": "Seite im echten Browser oeffnen", "en": "Open page in real browser"},
    "manual.o_long": {"de": "'o' uebergibt die aktuelle Seite an den Browser des Betriebssystems, 'o 5' stattdessen das Ziel von Link Nr. 5. Nuetzlich fuer Seiten, die im Terminal nicht darstellbar sind — Videos, Karten, Logins.", "en": "'o' hands the current page to the operating system's browser; 'o 5' opens the target of link no. 5 instead. Useful for pages the terminal cannot show — videos, maps, logins."},

    "manual.dl_short": {"de": "ZMODEM-Download nach ~/bbs_downloads", "en": "ZMODEM download to ~/bbs_downloads"},
    "manual.dl_long": {"de": "'dl' speichert die aktuelle Seite als Textdatei, 'dl 5' laedt stattdessen das Ziel von Link Nr. 5 herunter. Der Transfer laeuft mit einem ZMODEM-Fortschrittsbalken und landet in der File Area ~/bbs_downloads/.", "en": "'dl' saves the current page as a text file; 'dl 5' downloads the target of link no. 5 instead. The transfer runs with a ZMODEM progress bar and lands in the file area ~/bbs_downloads/."},

    "manual.a_short": {"de": "Aktuelle Seite als Favorit speichern", "en": "Save current page as favorite"},
    "manual.a_long": {"de": "Legt die aktuelle Seite im Bookmark-Register ab. Favoriten erscheinen im Hauptmenue und sind per Kurzwahl 'd <nr>' erreichbar.", "en": "Adds the current page to the bookmark register. Favorites appear in the main menu and are reachable via quick dial 'd <no>'."},

    "manual.m_short": {"de": "Bookmark-Menue", "en": "Bookmark menu"},
    "manual.m_long": {"de": "Zeigt alle Favoriten mit Nummer. Eine Nummer waehlt an, 'x <nr>' loescht einen Eintrag.", "en": "Shows all favorites with number. A number selects it; 'x <no>' deletes an entry."},

    "manual.home_short": {"de": "Zurueck zum Hauptmenue", "en": "Back to main menu"},
    "manual.home_long": {"de": "Zeigt die zweispaltige Hauptmenue-Tafel erneut an: Favoriten links, letzte Besuche rechts. Dieselbe Tafel, die beim Start ohne URL erscheint.", "en": "Shows the two-column main menu board again: favorites on the left, recent visits on the right. The same board that appears at startup without a URL."},

    "manual.h_short": {"de": "Verlauf anzeigen oder Eintrag anwaehlen", "en": "Show history or select entry"},
    "manual.h_long": {"de": "'h' listet die letzten Anwahlen, neueste zuerst und ohne Doppelte. 'h 3' waehlt Eintrag Nr. 3 erneut an. Dieselbe Liste steht im Hauptmenue rechts.", "en": "'h' lists recent visits, newest first and without duplicates. 'h 3' selects entry no. 3 again. The same list appears in the main menu on the right."},

    "manual.sum_short": {"de": "Seite vom SysOp zusammenfassen lassen", "en": "Have SysOp summarize page"},
    "manual.sum_long": {"de": "Der KI-SysOp liest die aktuelle Seite und fasst sie als knappen Digest fuer eilige Anrufer zusammen. Braucht einen API-Key (siehe 'ai').", "en": "The AI SysOp reads the current page and summarizes it as a brief digest for busy callers. Requires an API key (see 'ai')."},

    "manual.ask_short": {"de": "Frage zur aktuellen Seite stellen", "en": "Ask question about current page"},
    "manual.ask_long": {"de": "Stellt dem SysOp eine Frage zum Inhalt der geladenen Seite. Wenn die Seite die Antwort nicht hergibt, sagt er das ehrlich.", "en": "Asks the SysOp a question about the content of the loaded page. If the page doesn't contain the answer, he says so honestly."},

    "manual.go_short": {"de": "SysOp navigiert zum passenden Link", "en": "SysOp navigates to matching link"},
    "manual.go_long": {"de": "Beschreibe, wo du hin willst ('go artikel ueber ki'), und der SysOp sucht den passenden Link auf der Seite und folgt ihm. Sieht die Eingabe wie eine URL aus, wird sie direkt angewaehlt.", "en": "Describe where you want to go ('go article about ai'), and the SysOp finds the matching link on the page and follows it. If the input looks like a URL, it's selected directly."},

    "manual.w_short": {"de": "Wer ist online (WHO)", "en": "Who is online (WHO)"},
    "manual.w_long": {"de": "Listet die Anrufer, die gerade in der Mailbox haengen: Nummer, Node, Handle, Baudrate, Idle-Zeit und was sie tun. Jeder Anrufer ist eine KI-Persona, die fest im Jahr 1989 lebt. Die Personas werden einmal erfunden und dauerhaft gespeichert (bis zu 20 Stueck); pro Session waehlt sich eine zufaellige Handvoll davon ein. Braucht einen API-Key.", "en": "Lists the callers currently dialed into the board: number, node, handle, baud rate, idle time and what they're doing. Each caller is an AI persona living firmly in 1989. Personas are invented once and stored permanently (up to 20); each session a random handful of them dials in. Requires an API key."},

    "manual.p_short": {"de": "Privatchat mit einem Anrufer", "en": "Private chat with a caller"},
    "manual.p_long": {"de": "'p 3' oeffnet einen 1:1-Chat mit Anrufer Nr. 3 aus der 'w'-Liste. Der Gespraechspartner kennt nichts nach 1989 — kein Internet, keine Handys — und haelt dich fuer einen anderen Modem-Nutzer. Der Verlauf wird pro Handle gespeichert: triffst du denselben Anrufer spaeter wieder, erinnert er sich. Leere Zeile oder 'exit' legt auf. Ab und zu klopft uebrigens auch jemand von sich aus an — nimmst du an, eroeffnet er den Chat gleich selbst mit der ersten Zeile.", "en": "'p 3' opens a 1:1 chat with caller no. 3 from the 'w' list. Your chat partner knows nothing past 1989 — no internet, no mobile phones — and takes you for another modem user. History is stored per handle: meet the same caller later and they'll remember. Empty line or 'exit' hangs up. Now and then someone will knock on your line unprompted, too — accept and they open the chat themselves with the first line."},

    "manual.x_short": {"de": "Hausvorlage der Domain setzen", "en": "Set the domain's house template"},
    "manual.x_long": {"de": "Setzt fuer die Domain der aktuellen Seite eine Hausvorlage: Der SysOp nimmt die Seite mit Setzerwerkzeugen auseinander (Satzprobe, Bauplan, Andruck) und ordnet die wiederkehrenden Bausteine der Website den Komponenten des Setzkastens zu — Plakat-Titel, Rubrikenbalken, Schild mit Schlagschatten, Hinweisbalken, Kasten, Ticker-Zeile, Trennlinie, Zitat, Infobox. Der Entwurf wird dabei an bis zu drei weiteren Fahnen derselben Domain angedruckt und nachgebessert; geholt werden die ueber dieselbe Leitung, mit der auch angewaehlt wird (Firecrawl, sonst Playwright, sonst HTTP). Die Arbeit sind die Titel und die grossen Textstrecken: Marken, die statt einer Ueberschrift einen ganzen Container greifen, lehnt die Presse ab, damit kein Inhalt verschwindet — auch Bilder zaehlen dabei als Inhalt und werden mitgezaehlt. Die fertige Vorlage liegt in der Datenbank und wird danach OHNE jeden weiteren KI-Aufruf auf alle Seiten der Domain angewendet; bei der Anwahl meldet der Schirm, wenn sie im Satz steckt. Ein erneutes 'x' setzt sie neu, 'x -' schmilzt sie ein. Ohne KI-Key ist 'x' nicht verfuegbar (Key setzen unter 'c' > KI). Suchergebnisse, RSS, Bulletins, Wetter, Gopher/Gemini und interne Schirme haben kein HTML und bekommen keine Vorlage. Setzkasten und Automatik: 'c' > KI > Hausvorlagen.", "en": "Sets a house template for the current page's domain: the SysOp takes the page apart with the print shop's tools (type sample, blueprint, proof run) and maps the site's recurring building blocks to the components in the type case — poster title, section bar, shadowed plaque, notice bar, framed box, ticker line, rule, quote, info box. The draft is proofed against up to three further galleys of the same domain and corrected; those are fetched over the same line the browser dials with (Firecrawl, else Playwright, else HTTP). The work is the titles and the large bodies of text: a mark grabbing a whole container instead of a heading is refused by the press, so no content vanishes — pictures count as content and are tallied too. The finished template lives in the database and is then applied to every page of that domain WITHOUT any further AI call; dialing reports when it is in the forme. Another 'x' resets it, 'x -' melts it down. Without an AI key, 'x' isn't available (set a key under 'c' > AI). Search results, RSS, bulletins, weather, Gopher/Gemini and internal screens carry no HTML and get no template. Type case and automatic mode: 'c' > AI > House templates."},

    "manual.log_short": {"de": "Gespeicherte Chatverlaeufe", "en": "Stored chat logs"},
    "manual.log_long": {"de": "'log' listet alle gespeicherten Gespraeche — den SysOp-Chat und jeden Privatchat mit einem Anrufer, jeweils mit Zeilenzahl und letzter Aktivitaet. 'log <nr>' liest einen Verlauf nach, 'log <nr> chat' steigt wieder in genau dieses Gespraech ein, 'log del <nr>' loescht ihn, 'log clear' raeumt alles weg. Die Verlaeufe liegen in der Datenbank und ueberdauern das Aufhaengen.", "en": "'log' lists all stored conversations — the SysOp chat and every private chat with a caller, each with line count and last activity. 'log <no>' reads a log, 'log <no> chat' jumps back into that very conversation, 'log del <no>' deletes it, 'log clear' wipes everything. Logs live in the database and survive hanging up."},
    "manual.chat_short":{"de": "Mit dem SysOp plaudern", "en": "Chat with SysOp"},
    "manual.chat_long": {"de": "Gespraeche mit dem SysOp — davon gibt es beliebig viele nebeneinander, wie Threads auf einer Message Base. 'chat' oeffnet das Chat-Board: eine Lightbar-Liste aller Gespraeche mit Titel, Zeilenzahl und letzter Aktivitaet ('n' beginnt ein neues, 'x' loescht das markierte, Enter steigt ein). Ohne gespeicherte Gespraeche geht es direkt ins erste. Der SysOp benennt ein neues Gespraech nach dem ersten Austausch selbst nach seinem Thema; '/name <Titel>' setzt den Namen von Hand. Im Chat wechselt '/neu' in ein frisches Gespraech und '/chats' zurueck aufs Board. Der SysOp kennt den Inhalt der Seite, die du gerade auf dem Schirm hast, und kann waehrend des Gespraechs selbst surfen, suchen und Links folgen — auch im Hintergrund recherchieren, ohne deinen Schirm zu veraendern. Leere Zeile oder 'exit' beendet. 'chat neu' beginnt direkt ein neues Gespraech, 'chat <nr>' steigt wieder in einen alten Verlauf ein — die Nummer kommt aus der Liste von 'log'.", "en": "Conversations with the SysOp — any number of them side by side, like threads on a message base. 'chat' opens the chat board: a lightbar list of all conversations with title, line count and last activity ('n' starts a new one, 'x' deletes the highlighted one, Enter joins). With no stored conversations it drops you straight into the first. The SysOp names a new conversation after its topic once the first exchange is done; '/name <title>' sets the name by hand. Inside the chat, '/new' switches to a fresh conversation and '/chats' returns to the board. The SysOp knows the content of the page you're currently viewing and can surf, search, and follow links during the chat — even research in the background without changing your screen. Empty line or 'exit' ends it. 'chat new' starts a new conversation directly, 'chat <no>' jumps back into an old one — the number comes from the 'log' list."},


    "manual.ai_short": {"de": "SysOp-Status, Anbieter, Key und Modell", "en": "SysOp status, provider, key, and model"},
    "manual.ai_long": {"de": "'ai' zeigt, ob der SysOp online ist, ueber welchen Anbieter (Anthropic direkt, Vercel AI Gateway oder OpenAI) und mit welchem Modell; darunter, welche Anbieter einen Key hinterlegt haben. 'ai provider <name>' schaltet zwischen anthropic, vercel und openai um. 'ai key <key>' hinterlegt den Schluessel beim aktiven Anbieter (vck_/sk-ant- schalten automatisch passend um), 'ai model <name>' waehlt ein anderes Modell. Firecrawl-MCP-Scrapes brauchen den Anbieter 'anthropic'. Standard-Modell je Anbieter: Claude Haiku 4.5 (Anthropic), DeepSeek V4 Flash (Vercel) bzw. GPT-4o mini (OpenAI).", "en": "'ai' shows whether the SysOp is online, via which provider (Anthropic directly, Vercel AI Gateway, or OpenAI), and with which model; plus which providers have a key stored. 'ai provider <name>' switches between anthropic, vercel, and openai. 'ai key <key>' stores the key for the active provider (vck_/sk-ant- switch the provider automatically); 'ai model <name>' chooses a different model. Firecrawl MCP scrapes require the 'anthropic' provider. Default model per provider: Claude Haiku 4.5 (Anthropic), DeepSeek V4 Flash (Vercel), or GPT-4o mini (OpenAI)."},

    "manual.u_short": {"de": "Token-Verbrauch und Kosten", "en": "Token usage and costs"},
    "manual.u_long": {"de": "Zeigt, wie viele Tokens der SysOp verbraucht hat — fuer diese Sitzung und insgesamt — mit Anzahl der Calls und den geschaetzten Kosten in Cent, berechnet aus dem Preis des aktuellen Modells. Gezaehlt wird alles: Zusammenfassungen, Fragen, Chat und MCP-Scrapes. Cache-Treffer tauchen nicht auf, weil sie nichts kosten. 'u reset' setzt den Gesamtzaehler zurueck.", "en": "Shows how many tokens the SysOp has used — for this session and total — with count of calls and estimated costs in cents, calculated from the price of the current model. Everything counts: summaries, questions, chat, and MCP scrapes. Cache hits don't show because they cost nothing. 'u reset' resets the total counter."},

    "manual.fc_short": {"de": "Firecrawl-Check", "en": "Firecrawl check"},
    "manual.fc_long": {"de": "Prueft die Firecrawl-Einrichtung, ohne Credits zu verbrauchen: aktiviert, Modus (SDK oder MCP), SDK installiert, Schluessel vorhanden und gueltig, Host beziehungsweise Cloud erreichbar. Jede Zeile ist mit OK, WARN oder FEHL markiert.", "en": "Checks Firecrawl setup without consuming credits: enabled, mode (SDK or MCP), SDK installed, key present and valid, host or cloud reachable. Each line is marked OK, WARN, or FAIL."},

    "manual.c_short": {"de": "Konfigurationsmenue", "en": "Configuration menu"},
    "manual.c_long": {"de": "Das verschachtelte Einstellungsmenue mit mehreren Bereichen: KI-SysOp (Key, Modell, Standard-Prompt mit eigenen Zusatzanweisungen, Hausvorlagen), Bulletins (News-Quellen, Kadenz, Anzahl), Firecrawl (an/aus, Modus, Key, Host, Check), Anzeige (Bilder, Bildbreite, Tipp-Effekt, Farbe, Baud-Simulation, Sound, darin auch ein eigener Punkt zum Zuruecksetzen nur der Anzeigeeinstellungen) und Systemzugriff (ob der SysOp Shell-Befehle ausfuehren darf: aus, mit Rueckfrage oder frei, dazu ein Zeitlimit) und MCP-Server (eigene Werkzeugserver fuer den SysOp registrieren, Anmeldung wahlweise per Bearer-Token oder OAuth). Im Hauptmenue setzt Reset saemtliche Einstellungen auf die Standardwerte zurueck. Enter geht jeweils eine Ebene zurueck.", "en": "The nested settings menu with several areas: AI SysOp (key, model, default prompt with your own extra instructions, house templates), Bulletins (news sources, cadence, count), Firecrawl (on/off, mode, key, host, check), Display (images, image width, typing effect, color, baud simulation, sound, with its own entry to reset just the display settings), and System access (whether the SysOp may run shell commands: off, ask first, or free, plus a timeout), and MCP servers (register your own tool servers for the SysOp, signing in with a bearer token or OAuth). In the main menu, Reset restores all settings to their defaults. Enter goes back one level each time."},

    "manual.i_short": {"de": "Bildmodus wechseln", "en": "Cycle image mode"},
    "manual.i_long": {"de": "Wechselt den Bildmodus: Halbbloecke (fein), ASCII-Zeichen oder aus. Nicht zeigenswerte Bilder — Logos, Icons, Tracking-Pixel, kontrastarme Flaechen, extreme Banner-Formate — werden ohnehin automatisch uebersprungen.", "en": "Cycles the image mode: half blocks (fine), ASCII chars, or off. Non-displayable images — logos, icons, tracking pixels, low-contrast areas, extreme banner formats — are skipped automatically anyway."},

    "manual.t_short": {"de": "Tipp-Effekt an/aus", "en": "Typing effect on/off"},
    "manual.t_long": {"de": "Schaltet die Schreibmaschinen-Ausgabe um. Aus heisst: alles erscheint sofort.", "en": "Toggles typewriter output. Off means: everything appears instantly."},

    "manual.sv_short": {"de": "Matrix-Screensaver", "en": "Matrix screensaver"},
    "manual.game_short": {"de": "Spielhalle oeffnen", "en": "Open the arcade"},
    "manual.game_long": {"de": "'game' zeigt die Spielhalle mit allen Spielen und deinen Rekorden. Der Name startet direkt, z.B. 'game snake' — oder einfach 'snake'. Angeboten werden Paddle, Stacker, Snake und Bricks. Die Bestenliste steht in der State-Datei unter 'games' und ueberlebt das Auflegen. Alle Spiele brauchen ein echtes Terminal.", "en": "'game' opens the arcade with all games and your records. The name starts one directly, e.g. 'game snake' — or just 'snake'. On offer are Paddle, Stacker, Snake and Bricks. The high score table lives in the state file under 'games' and survives hanging up. All games need a real terminal."},

    "manual.pong_short": {"de": "Paddle gegen den Rechner", "en": "Paddle duel against the computer"},
    "manual.pong_long": {"de": "Klassisches Paddle-Duell im Textmodus. Dein Schlaeger steht links: 'w'/'s' oder Pfeil hoch/runter bewegen ihn, der Auftreffpunkt bestimmt den Abprallwinkel. Wer zuerst 7 Punkte hat, gewinnt; 'q' bricht ab. Gezaehlt wird deine Punktzahl als Rekord.", "en": "A classic paddle duel in text mode. Your paddle is on the left: 'w'/'s' or arrow up/down move it, and where the ball hits decides the bounce angle. First to 7 points wins; 'q' quits. Your points count as the record."},

    "manual.tetris_short": {"de": "Stacker im Terminal", "en": "Stacker in the terminal"},
    "manual.tetris_long": {"de": "Stacker auf einem 10x20-Feld. 'a'/'d' oder Pfeil links/rechts schieben, 'w' oder Pfeil hoch dreht (mit Wandausweichen), 's' laesst schneller fallen, die Leertaste wirft hart ab, 'q' bricht ab. Volle Reihen bringen Punkte, alle 10 Reihen steigt das Level und der Stein faellt schneller.", "en": "Stacker on a 10x20 field. 'a'/'d' or arrow left/right move, 'w' or arrow up rotates (with wall kicks), 's' soft-drops, space hard-drops, 'q' quits. Full rows score points; every 10 rows the level rises and pieces fall faster."},

    "manual.snake_short": {"de": "Snake — Happen sammeln", "en": "Snake — collect the food"},
    "manual.snake_long": {"de": "Snake auf einem 29x17-Feld. 'w'/'a'/'s'/'d' oder die Pfeiltasten lenken, eine Kehrtwende in den eigenen Hals wird ignoriert. Jeder Happen bringt 10 Punkte, verlaengert die Schlange und macht sie ein Stueck schneller. Wand oder eigener Koerper beenden das Spiel, 'q' bricht ab.", "en": "Snake on a 29x17 field. 'w'/'a'/'s'/'d' or the arrow keys steer; a U-turn into your own neck is ignored. Each bite scores 10 points, grows the snake and speeds it up a little. Wall or own body ends the game, 'q' quits."},

    "manual.space_short": {"de": "Sternenkurier — Handels-Door im All", "en": "Star Courier — space trading door"},
    "manual.space_long": {"de": "Das Handels-Door der Mailbox: zwoelf Sektoren auf einem Ring, jeder mit eigenen Tagespreisen fuer Erz, Isotope und Schaltwerk. 'space' (auch 'game space') oeffnet die Bruecke. Pro Tag gibt es 20 Treibstoff; jeder Warpsprung kostet soviel wie die Distanz auf dem Ring, und auf den Routen lauern Piraten — darunter die anderen Anrufer aus 'w'. Gewinne fliessen in Laser, Schilde und einen groesseren Laderaum; das Stationsbuero flickt die Huelle, verkauft Nanokits und verwahrt Credits auf dem Konto, damit ein Abschuss sie nicht mitnimmt. Ab der Plasmabatterie wartet im Wrackfeld der Hohle Koloss. Das Schiff liegt in der Datenbank und ueberlebt das Auflegen; wer abgeschossen wird, fliegt am naechsten Tag wieder — ohne Fracht und Bordkasse.", "en": "The mailbox trading door: twelve sectors on a ring, each with its own daily prices for ore, isotopes and circuitry. 'space' (also 'game space') opens the bridge. You get 20 fuel per day; every warp jump costs its ring distance, and pirates prowl the lanes — among them the other callers from 'w'. Profits go into lasers, shields and a bigger hold; the station office patches the hull, sells nanokits and keeps credits in the account so getting shot down cannot take them. From the plasma battery up, the Hollow Colossus waits in the wreck field. The ship lives in the database and survives hanging up; whoever gets shot down flies again the next day — without cargo and cash aboard."},
    "manual.dragon_short": {"de": "Der Uralte Wurm — Door Game", "en": "The Ancient Wyrm — door game"},
    "manual.dragon_long": {"de": "Das Door Game der Mailbox: ein Rollenspiel im Geist der BBS-Klassiker. 'dragon' (auch 'game dragon') oeffnet den Dorfplatz. Pro Tag stehen 15 Waldkaempfe zur Verfuegung; dazwischen kaufst du beim Waffenschmied und in der Ruestkammer, laesst dich im Wirtshaus flicken und legst Gold in die Truhe, damit es der Tod nicht mitnimmt. Genug Erfahrung? Dann fordert dich der Meister zum Aufstieg. Mit Rang 12 steht der Uralte Wurm bereit. Im Wald laufen dir auch die anderen Anrufer aus 'w' ueber den Weg. Der Charakter liegt in der Datenbank und ueberlebt das Auflegen; wer stirbt, steht am naechsten Tag wieder auf — ohne das Gold, das er bei sich trug.", "en": "The mailbox door game: a role-playing game in the spirit of the BBS classics. 'dragon' (also 'game dragon') opens the village square. You get 15 forest fights per day; in between you shop at the weapon smith and the armoury, get patched up at the tavern and put gold in the chest so death cannot take it. Enough experience? Then your master challenges you for the next rank. At rank 12 the Ancient Wyrm is waiting. In the forest you also run into the other callers from 'w'. The character lives in the database and survives hanging up; whoever dies rises again the next day — without the gold they carried."},
    "manual.breakout_short": {"de": "Bricks — Mauer abraeumen", "en": "Bricks — clear the wall"},
    "manual.breakout_long": {"de": "Bricks mit fuenf Ziegelreihen und drei Leben. 'a'/'d' oder Pfeil links/rechts schieben den Schlaeger, der Auftreffpunkt lenkt den Ball. Die oberen Reihen bringen mehr Punkte (50 bis 10), fuer jedes uebrige Leben am Ende gibt es 100 Bonuspunkte. 'q' bricht ab.", "en": "Bricks with five brick rows and three lives. 'a'/'d' or arrow left/right move the paddle, and where the ball hits steers it. Upper rows score more (50 down to 10), and every life left at the end is worth 100 bonus points. 'q' quits."},

    "manual.sv_long": {"de": "Startet den Matrix-Regen sofort ('matrix' geht auch). Er kommt ausserdem von selbst, wenn am Hauptprompt eine Weile nichts passiert — Standard sind 300 Sekunden, einstellbar unter k, Anzeige, Screensaver (0 = aus). Eine beliebige Taste beendet ihn.", "en": "Starts the Matrix rain immediately ('matrix' works too). It also comes on its own if nothing happens at the main prompt for a while — default is 300 seconds, adjustable under k, Display, Screensaver (0 = off). Any key stops it."},

    "manual.help_short": {"de": "Hilfe", "en": "Help"},
    "manual.help_long": {"de": "'?' zeigt die Befehlsuebersicht. '? l' oder '? chat' erklaert einen einzelnen Befehl ausfuehrlich. Dasselbe Handbuch nutzt auch der SysOp, wenn du ihn im Chat nach einer Funktion fragst.", "en": "'?' shows the command overview. '? l' or '? chat' explains a single command in detail. The SysOp uses the same handbook when you ask him about a function in chat."},

    "manual.up_short": {"de": "Selbst-Update aus Git", "en": "Self-update from Git"},
    "manual.up_long": {"de": "Prueft die neueste Release auf GitHub, laedt bei einer neueren Version das fertige Paket (Wheel) herunter und installiert 'bbs' neu — bevorzugt ueber pipx (inkl. KI-SDK), sonst per pip in die aktuelle Umgebung. Braucht kein git, nur Netz. Bist du schon aktuell, passiert nichts. Steht eine neue Version bereit, weist das Hauptmenue darauf hin. Nach dem Update 'bbs' neu starten. Die Releases entstehen automatisch bei jedem Merge nach main.", "en": "Checks the latest release on GitHub, downloads the prebuilt package (wheel) if a newer version exists, and reinstalls 'bbs' — preferring pipx (including the AI SDK), otherwise pip into the current environment. Needs no git, only network. If you are already up to date, nothing happens. When a new version is available, the main menu points it out. Restart 'bbs' after the update. Releases are produced automatically on every merge into main."},

    "manual.q_short": {"de": "Auflegen", "en": "Hang up"},
    "manual.q_long": {"de": "Beendet die Sitzung mit NO CARRIER — nach einer Rueckfrage (j/n). Favoriten und Verlauf werden gespeichert.", "en": "Ends the session with NO CARRIER — after a confirmation (y/n). Bookmarks and history are saved."},

    # CONCEPTS

    "manual.concept_main_menu": {"de": "Hauptmenue", "en": "Main menu"},
    "manual.concept_main_menu_short": {"de": "Das Main Board beim Start", "en": "The main board at startup"},
    "manual.concept_main_menu_long": {"de": "Startest du ohne URL, erscheint die zweispaltige Tafel: links die Favoriten mit Kurzwahl-Nummern, rechts die letzten Besuche. Darunter eine Statuszeile mit Handle, Anrufer-Nummer, aktiver Node und Zaehlern.", "en": "If you start without a URL, a two-column board appears: favorites with quick dial numbers on the left, recent visits on the right. Below that, a status line with handle, caller number, active node, and counters."},

    "manual.concept_typecase": {"de": "Der Setzkasten", "en": "The type case"},
    "manual.concept_typecase_short": {"de": "Die BBS-Komponenten des Renderers", "en": "The renderer's BBS components"},
    "manual.concept_typecase_long": {"de": "Jede Seite wird einspaltig ueber die volle Schirmbreite gesetzt — ein Terminal liest man in einer Spalte. Zum Gestalten hat der Renderer einen festen Setzkasten: banner (Plakat-Titel in Blockschrift), heading (fette Ueberschrift mit Unterstrich), topicbar (Rubrikenbalken, Titel in der Linie), ticker (gedimmte Einzeile zwischen Pfeilen, fuer Datums-, Dach- und Autorenzeile), plaque (Kasten mit Schlagschatten), notice (Hinweis am fetten Balken), frame (doppelter Kasten), infobox (Schluessel/Wert-Kasten), rule (Trennlinie), quote (Zitat), pre (Code) und text (Fliesstext). Normale Seiten setzt die Heuristik daraus; eine Hausvorlage ('x') ordnet die Bausteine einer Website gezielt diesen Komponenten zu. Erfinden kann die KI nichts — es gibt genau diesen Kasten.", "en": "Every page is set in one column across the full screen width — a terminal is read in one column. For layout the renderer holds a fixed type case: banner (poster title in block lettering), heading (bold heading with a rule), topicbar (section bar with the title set into the rule), ticker (dimmed one-liner between arrows, for datelines, kickers and bylines), plaque (box with a drop shadow), notice (callout on a solid bar), frame (double-line box), infobox (key/value box), rule (divider), quote, pre (code) and text (body copy). Ordinary pages are set from it by the heuristic; a house template ('x') maps a site's building blocks onto these components deliberately. The AI cannot invent one — this case is all there is."},

    "manual.concept_aria": {"de": "ARIA-Auswertung", "en": "ARIA evaluation"},
    "manual.concept_aria_short": {"de": "Saubere Inhaltserkennung", "en": "Clean content detection"},
    "manual.concept_aria_long": {"de": "Beim Parsen werden ARIA-Angaben genutzt, wenn vorhanden: aria-hidden-Elemente und Landmark-Rollen wie navigation oder banner fliegen raus, role=main dient als Inhalts-Wurzel, aria-label liefert Beschriftungen fuer Links ohne sichtbaren Text.", "en": "When parsing, ARIA attributes are used if present: aria-hidden elements and landmark roles like navigation or banner are removed, role=main serves as content root, aria-label provides labels for links without visible text."},

    "manual.concept_color": {"de": "Intelligenter Farbmodus", "en": "Intelligent color mode"},
    "manual.concept_color_short": {"de": "Phosphor-Ton pro Seite", "en": "Phosphor tone per page"},
    "manual.concept_color_long": {"de": "Im Modus AUTO (k, Anzeige, Farbe) toent sich der Bildschirm pro Seite: aus der theme-color der Seite wird der naechstgelegene Phosphor-Ton gewaehlt — Amber, Gruen, Cyan, Blau, Magenta oder Rot. Fehlt eine brauchbare Markenfarbe, bekommt jede Domain stabil ihre eigene Farbe. Der Modus MULTI faerbt stattdessen nach Rollen wie ein klassisches ANSI-BBS: Fliesstext grau, Titel und Linkmarker gelb, Rahmen und Linien blau — und Bilder erscheinen in Echtfarbe.", "en":"In AUTO mode (k, Display, Color) the screen tones per page: from the page's theme-color, the nearest phosphor tone is chosen — amber, green, cyan, blue, magenta, or red. If no usable brand color exists, each domain stably gets its own color. MULTI mode instead colors by role like a classic ANSI BBS: body copy gray, titles and link markers yellow, frames and rules blue — and images appear in real color."},

    "manual.concept_baud": {"de": "Baud-Simulation", "en": "Baud simulation"},
    "manual.concept_baud_short": {"de": "Seiten trudeln ein wie am Modem", "en": "Pages arrive like on a modem"},
    "manual.concept_baud_long": {"de": "Unter k, Anzeige, Baud waehlst du 2400 oder 9600 Baud (Standard: 9600, AUS ist volle Geschwindigkeit). Der Text laeuft dann zeichenweise mit passender Geschwindigkeit ein. Farbcodes kosten keine Zeit, das Timing bleibt echt.", "en": "Under k, Display, Baud you choose 2400 or 9600 baud (default: 9600, OFF is full speed). Text then scrolls character-by-character at appropriate speed. Color codes cost no time; the timing stays authentic."},

    "manual.concept_sound": {"de": "Sound", "en": "Sound"},
    "manual.concept_sound_short": {"de": "Terminal-Glocke", "en": "Terminal bell"},
    "manual.concept_sound_long": {"de": "Ist Sound an (k, Anzeige), piept das Terminal beim Verbindungsaufbau und bei Fehlern.", "en": "When sound is on (k, Display), the terminal beeps on connect and errors."},


    "manual.concept_firecrawl": {"de": "Firecrawl", "en": "Firecrawl"},
    "manual.concept_firecrawl_short": {"de": "JS-lastige Seiten scrapen", "en": "Scrape JS-heavy pages"},
    "manual.concept_firecrawl_long": {"de": "Firecrawl holt Seiten, die ohne JavaScript zu wenig hergeben. Zwei Modi: SDK direkt (eigener Key, optional eigener Host beim Self-Hosting) oder MCP via KI, bei dem der SysOp Firecrawl als MCP-Server laedt und automatisch nachscraped. Ist Firecrawl aktiviert, uebernimmt es das JS-Rendering allein — das lokale Playwright-Chromium bleibt dann aussen vor; scheitert ein Abruf, geht es direkt per HTTP weiter und der Grund wird gemeldet. Ist Firecrawl konfiguriert, laufen auch die Suche ('s') und die Netz-Recherche des SysOp ueber die Firecrawl-Such-API statt ueber DuckDuckGo. Pruefen mit 'fc'.", "en": "Firecrawl fetches pages that don't yield enough without JavaScript. Two modes: SDK direct (own key, optionally own host for self-hosting) or MCP via AI, where the SysOp loads Firecrawl as an MCP server and auto-scrapes. When Firecrawl is enabled, it handles JS rendering alone — the local Playwright Chromium stays out of the picture; if a fetch fails, the browser falls back to plain HTTP and reports the reason. When Firecrawl is configured, search ('s') and the SysOp's net research also use the Firecrawl search API instead of DuckDuckGo. Check with 'fc'."},

    "manual.concept_login": {"de": "Login und Anrufer-Zaehler", "en": "Login and caller counter"},
    "manual.concept_login_short": {"de": "Handle und Statistik", "en": "Handle and statistics"},
    "manual.concept_login_long": {"de": "Beim ersten Start fragt die BBS nach deinem Handle. Danach begruesst sie dich bei jeder Anwahl mit Anrufer-Nummer, Node und dem Zeitpunkt der letzten Anwahl.", "en": "On first startup, the BBS asks for your handle. After that, it greets you on every call with caller number, node, and time of last visit."},

    "manual.concept_links_tool": {"de": "bbs --links", "en": "bbs --links"},
    "manual.concept_links_tool_short": {"de": "Linkliste auf der Kommandozeile", "en": "Link list on command line"},
    "manual.concept_links_tool_long": {"de": "'bbs --links <url>' gibt nur die nummerierte Linkliste einer Seite aus und beendet sich — ohne Terminal-Schnickschnack, gut fuer Skripte und Pipes.", "en": "'bbs --links <url>' outputs only the numbered link list of a page and exits — no terminal frills, good for scripts and pipes."},

    # overview() text
    "manual.overview_title": {"de": "BEFEHLSUEBERSICHT", "en": "COMMAND OVERVIEW"},
    "manual.overview_separator": {"de": "-----------------", "en": "-----------------"},
    "manual.overview_footer_1": {"de": "'? <befehl>' erklaert einen Befehl ausfuehrlich, z.B. '? rss'.", "en": "'? <command>' explains a command in detail, e.g. '? rss'."},
    "manual.overview_footer_2": {"de": "Beim -- MORE -- Prompt: Enter=weiter, q=Seite abbrechen,", "en": "At -- MORE -- prompt: Enter=continue, q=stop page,"},
    "manual.overview_footer_3": {"de": "oder direkt eine Link-Nummer bzw. einen Befehl eingeben.", "en": "or enter a link number or command directly."},
}
